-- CREATE TABLE IF NOT EXISTS student (
--     id VARCHAR(100) PRIMARY KEY,
--     username VARCHAR(50) NOT NULL UNIQUE,
--     email VARCHAR(100) NOT NULL UNIQUE,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- ALTER TABLE student MODIFY COLUMN id VARCHAR(100);

-- drop TABLE student
-- DELETE FROM student;

SELECT * FROM student;